config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :raitings
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'}
  resources :raitings  
  
  get 'about', to: 'pages#about', as: 'about'
  
  resources :articles
  resources :availabilities
  resources :categories, except: [:destroy]
  get 'appointment/:id', to: 'appointment#show', as: 'appointment_show'
  post 'appointment/create'
  get 'lawyers', to: 'lawyer#index', as:"lawyers"
  get 'lawyer/:id', to: 'lawyer#show', as: 'lawyer_show'

  root 'articles#index'
end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :slot
  belongs_to :user
end

app/models/articule.rb
class Articule < ApplicationRecord
  belongs_to :user
  has_many :raitings
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true

  def self.average(articule)
    @avg= Rating.where(articule_id: articule).avg(point)
    return @avg
  end
end

app/models/articule_tag.rb
class ArticuleTag < ApplicationRecord
  belongs_to :tag
  belongs_to :articule
end

app/models/client.rb
class Client < User
    validates :full_name, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :articule
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :articule_tags
    has_many :articules, through: :article_tags
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,  omniauth_providers: [:google_oauth2]

def self.from_google(email:, full_name:, uid:, avatar_url:)
  create_with(uid: uid, full_name: full_name, avatar_url: avatar_url, password: Devise.friendly_token[0,20]).find_or_create_by!(email: email)
end

has_many :appointments
has_many :slots

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < InheritedResources::Base

  private

    def appointment_params
      params.require(:appointment).permit(:slot_id, :user_id, :client)
    end

end

app/controllers/articules_controller.rb
class ArticulesController < InheritedResources::Base

  private

    def articule_params
      params.require(:articule).permit(:title, :content, :user_id)
    end

end

app/controllers/ratings_controller.rb
class RatingsController < InheritedResources::Base

  private

    def rating_params
      params.require(:rating).permit(:point, :user_id, :articule_id)
    end

end

app/controllers/slots_controller.rb
class SlotsController < InheritedResources::Base

  private

    def slot_params
      params.require(:slot).permit(:available, :user_id, :day, :start, :end)
    end

end

app/controllers/tags_controller.rb
class TagsController < InheritedResources::Base

  private

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/articules_helper.rb
module ArticulesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/appointments/_form.html.erb
<%= form_with url: appointment_create_path, local: true do |form| %>
  <%= form.hidden_field :slot_id, id: 'slot-id' %>
  <div class="form-group">
    <label for="coach-name">abogado:</label>
    <%= form.text_field :lawyer_name, id: 'lawyer-name', class: 'form-control', disabled: true %>
  </div>
  <div class="form-group">
    <label for="slot-time">Cita:</label>
    <%= form.text_field :appointment, id: 'appointment', class: 'form-control', disabled: true %>
  </div>
  <div class="form-group">
    <%= form.submit 'Agendar', class: "btn btn-md btn-primary btn-block" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Slot</th>
      <th>User</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.slot %></td>
        <td><%= appointment.user %></td>
        <td><%= appointment.client %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slot:</strong>
  <%= @appointment.slot %>
</p>

<p>
  <strong>User:</strong>
  <%= @appointment.user %>
</p>

<p>
  <strong>Client:</strong>
  <%= @appointment.client %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/articules/_form.html.erb
<%= form_with(model: articule, local: true) do |form| %>
  <% if articule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(articule.errors.count, "error") %> prohibited this articule from being saved:</h2>

      <ul>
      <% articule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articules/edit.html.erb
<h1>Editing Articule</h1>

<%= render 'form', articule: @articule %>

<%= link_to 'Show', @articule %> |
<%= link_to 'Back', articules_path %>

app/views/articules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articules</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articules.each do |articule| %>
      <tr>
        <td><%= articule.title %></td>
        <td><%= articule.content %></td>
        <td><%= articule.user %></td>
        <td><%= link_to 'Show', articule %></td>
        <td><%= link_to 'Edit', edit_articule_path(articule) %></td>
        <td><%= link_to 'Destroy', articule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Articule', new_articule_path %>

app/views/articules/new.html.erb
<h1>New Articule</h1>

<%= render 'form', articule: @articule %>

<%= link_to 'Back', articules_path %>

app/views/articules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @articule.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @articule.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @articule.user %>
</p>

<%= link_to 'Edit', edit_articule_path(@articule) %> |
<%= link_to 'Back', articules_path %>

app/views/ratings/_form.html.erb
<%= form_with(model: rating, local: true) do |form| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :point %>
    <%= form.number_field :point %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :articule_id %>
    <%= form.text_field :articule_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Point</th>
      <th>User</th>
      <th>Articule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.point %></td>
        <td><%= rating.user %></td>
        <td><%= rating.articule %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Point:</strong>
  <%= @rating.point %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>Articule:</strong>
  <%= @rating.articule %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>

app/views/slots/_form.html.erb
<%= form_with(model: slot, local: true) do |form| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.text_field :day %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.text_field :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.text_field :end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slots</h1>

<table>
  <thead>
    <tr>
      <th>Available</th>
      <th>User</th>
      <th>Day</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.available %></td>
        <td><%= slot.user %></td>
        <td><%= slot.day %></td>
        <td><%= slot.start %></td>
        <td><%= slot.end %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

app/views/slots/new.html.erb
<h1>New Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Available:</strong>
  <%= @slot.available %>
</p>

<p>
  <strong>User:</strong>
  <%= @slot.user %>
</p>

<p>
  <strong>Day:</strong>
  <%= @slot.day %>
</p>

<p>
  <strong>Start:</strong>
  <%= @slot.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @slot.end %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>